[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
game_token = "DdhUfxGFwmaHrz5WsJ2jXM5Xts14ctytBvaQ8QoyqgGq"

[programs.mainnet]
game_token = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
    "programs/game_token",
    "programs/game_token_v2",
    "programs/simple_transfer"
]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
